networks:
  my_network:
    driver: bridge

volumes:
  photos:


services:
  db:
    build: ./db
    image: db-image
    networks:
      - my_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_db
    container_name: db-container

  api:
    depends_on:
      - db
    build: ./api
    image: api-image
    volumes:
      - photos:/api/photos
    networks:
      - my_network
    ports:
      - 8000:8000
    container_name: api-container
